# https://taskfile.dev

version: '3'

tasks:
  build:
    aliases:
      - default
    cmds:
      - task: minify-js
      - task: minify-css

  minify-js:
    sources:
      - src/script.js
      - src/script.min.js
    generates:
      - src/script.min.js
    cmds:
      - npx terser src/script.js --output src/script.min.js --compress --mangle
    description: Minify script.js to script.min.js

  minify-css:
    sources:
      - src/style.css
      - src/style.min.css
    generates:
      - src/style.min.css
    cmds:
      - cssnano src/style.css src/style.min.css

  bump:
    generates:
      - VERSION
      - CHANGELOG.md
    cmds:
      - cz bump

  push:
    vars:
      GIT_REPO_NAMES: [memory, github]
    preconditions:
      - test ! -f app/DEBUG
    cmds:
      - for: { var: GIT_REPO_NAMES }
        cmd:  git push {{.ITEM}} && git push {{.ITEM}} --tags