# https://taskfile.dev

version: '3'

tasks:
  build:
    aliases:
      - default
    cmds:
      - task: rollup-build

  rollup-build:
    sources:
      - src/**/*.js
      - src/**/*.mjs
      - src/**/*.css
      - rollup.config.mjs
    generates:
      - src/script.min.js
      - src/style.min.css
      - src/script.mins.js.map
    method: timestamp
    cmds:
      - npx rollup --config

  bump:
    generates:
      - VERSION
      - CHANGELOG.md
    cmds:
      - cz bump

  push:
    vars:
      GIT_REPO_NAMES: [memorymd, github]
    preconditions:
      - test ! -f app/DEBUG
    cmds:
      - for: { var: GIT_REPO_NAMES }
        cmd:  git push {{.ITEM}} && git push {{.ITEM}} --tags